### ISSUE TITLE
Notice: Undefined 

### ISSUE THREAD

**Issue by ystartgo** [XoopsModules25x/xlanguage#15] opened 2021-02-26 04:19 UTC
Notice: Undefined index: zh in the file at column 168 /modules/xlanguage/class/Utility.php

**Comment by ystartgo** [comment] 2021-02-26 04:33
My website language settings need to change the name, but the name is locked by default, I added a new language to the list to show this issue.
https://i.imgur.com/6qUr8ZQ.png

**Comment by mambax7** [comment] 2021-02-26 04:37
Is it only with "zh"? Because you have the same for "en", so if there is a problem in the code, then it should show for both? 
Or is something missing in the language files? 
I'm just trying to see how could I reproduce it here...

**Comment by mambax7** [comment] 2021-02-26 04:46
Is it maybe because you should not use the final code for the base language?
![image](https://user-images.githubusercontent.com/613686/109256161-6dd5fa80-77c3-11eb-954e-0aff70fdc423.png)

The instructions in help are:
```

- select basic languages (from an available language list) and add extended languages (upon a selected basic language) from module admin page
- for instance, to make language switch between: English, Simplified Chinese (gb2312), Traditional Chinese (big5) and UTF-8 Chinese:
- base 1: name: english; description(optional): English; charset: iso-8859-1; code: en (or anyother like "xen", not a true language code, just the tag for indicating English content)
- base 2: name: schinese; description(optional): Simplified Chinese; charset: gb2312; code: zh (or anyother like "sc", not a true language code, just the tag for indicating Chinese content)
- extended lang of schinese 1: name: tchinese; description(optional): Traditional Chinese; charset: big5 code: zh-TW (the true language code of Traditional Chinese) base: schinese
- extended lang of schinese 2: name: utf8; description(optional): Simplified Chinese UTF-8; charset: utf-8 code: zh-CN (the true language code of Simplified Chinese) base: schinese

```

**Comment by mambax7** [comment] 2021-03-08 04:28
Is it still an issue? If not, can you close it?

**Closed** 2021-03-19 01:23 UTC
